#87 statistic should include weight
ViktorNy/TheHousehold pull request #88
Opened 2021-11-02 16:15 UTC by 87rasnyg

closes #82

wrote extremly advanced code to make this happen. 
(I also wrote the wrong issue number in the branch name)

2021-11-02 16:38 UTC, GrodanBool approved these changes

2021-11-03 07:43 UTC, EmelieBrobergs approved these changes

2021-11-03 08:42 UTC, ViktorNy requested changes
File userActions, action should be renamed.

2021-11-03 10:06 UTC, Erik-wiklund submitted a review, later dismissed

2021-11-03 10:09 UTC, EmelieBrobergs approved these changes

2021-11-03 10:09 UTC, ViktorNy approved these changes

2021-11-03 10:09 UTC, merged